---
title: "Analysis of Available Data"
output: html_notebook
---
# Set-Up R Environment
```{r setup}
## Clear environment
#rm(list = ls())

## Libraries
library(dataRetrieval)
library(tidyverse)
library(openxlsx)
library(leaflet)                                           
library(reshape2)
library(knitr)
library(MazamaSpatialUtils)
library(scales)
#Set working directory
opts_knit$set(root.dir = "C:/Users/jbehr/OneDrive - Duke University/Documents/5. R/2._WQP-EllerbeC-FlatR")
```

# Download Data
```{r}
# NWIS Data
Upper_Neuse_Water<-read.csv("output/Data/WQP_Upper-Neuse_WATER.csv") #large file
Both_Water<-read.csv("output/Data/WQP_FR-EC_WATER.csv")
Both_Water_Plot_Data_2014<- read.csv("output/Data/WQP_FR-EC_WATER-2014.csv")

Upper_Neuse_Sites<-read.csv("output/Data/WQP_Upper-Neuse_SITES.csv")
Ellerbe_Flat_Sites<-read.csv("output/Data/WQP_FR-EC_SITES.csv")

# STORET Data
STORET_Data_EC_FR<-read.csv("output/Data/WQP_FR-EC_WATER_STORET.csv")

# Invertebrate Data
Inverts_Upper_Neuse<-read.csv("output/Data/Upper-Neuse_Inverts.csv")

# Flow Data
All_sites_flow<-read.csv("output/Data/Upper-Neuse_Inverts.csv")
```

# Analysis

### Rating Curve
```{r}
Rating_Curve<-All_sites_flow %>% 
  ggplot(aes(x= Gage_ft, y=Discharge_cu3sec, color = as.character(site_no))) +
  geom_point() +
  theme_classic() +
  scale_y_continuous(trans='log10') +
  theme(axis.text.x = element_text(angle=60, hjust = 1), legend.text=element_text(size=7)) +
  labs(title="Rating Curve for USGS Gages")
print(Rating_Curve)
```

### 2014 Analytes Detected, by Group

```{r}
Measurements_Grouped_2014<-Both_Water_Plot_Data_2014 %>% 
  filter(str_detect(MonitoringLocationIdentifier, 
                    c("02085500|02086849"))) %>% 
  ggplot(aes(x=MonitoringLocationIdentifier, fill = as.character(parameter_group_nm))) +
  geom_bar() +
  ylim(0, 4000) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle=45, hjust = 1)) + 
  labs(title="Total Measurements Taken in 2014", fill="Analyte Group Name")
print(Measurements_Grouped_2014)
##ggsave("output/Decades_EC.png")
  
Detections_2014<-Both_Water_Plot_Data_2014 %>% 
  filter(str_detect(MonitoringLocationIdentifier, 
                    c("02085500|02086849"))) %>% 
  ggplot(aes(x=MonitoringLocationIdentifier, fill = as.character(parameter_group_nm))) +
  geom_bar(position = "stack", stat = "count") +
  facet_wrap(~Detect_Status) +
  ylim(0, 4000) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle=45, hjust = 1)) + 
  labs(title="Non-Detects, 2014", fill="Analyte Group Name")
print(Detections_2014)

# Manipulate data for easier plot
Both_Water_Plot_Data_2014$parameter_group_nm<-as.character(Both_Water_Plot_Data_2014$parameter_group_nm)

Detect_Percent_Data<- Both_Water_Plot_Data_2014 %>%
  filter(str_detect(MonitoringLocationIdentifier, 
                    c("02085500|02086849"))) %>% 
  filter(!is.na(parameter_group_nm)) %>% 
  filter(!str_detect(parameter_group_nm, 
                    "Information|Physical|Sediment|Stable")) %>%
  mutate(parameter_group_nm = str_replace_all(parameter_group_nm, 
                              "Inorganics, Major, Non-metals|Inorganics, Major, Metals|Inorganics, Minor, Metals",
                              "Inorganics")) %>% 
  group_by(USGSPCode, MonitoringLocationName) %>% 
  mutate(Code_Detect_Count=sum(!is.na(ResultMeasureValue))) %>%
  filter(Code_Detect_Count!= 0) %>% 
  group_by(parameter_group_nm, MonitoringLocationName) %>% 
  mutate(Detect_Count=sum(!is.na(ResultMeasureValue))) %>% 
  mutate(Non_Detect_Count=sum(is.na(ResultMeasureValue))) %>%
  mutate(Percent_Detected=((Non_Detect_Count)/(Detect_Count+Non_Detect_Count))
         *100) %>% 
  distinct(MonitoringLocationName, parameter_group_nm, .keep_all=TRUE) 

# Plots
Detection_Percent<- Detect_Percent_Data %>% 
  ungroup() %>% 
  mutate(MonitoringLocationName = str_replace_all(MonitoringLocationName, 
                              "ELLERBE CREEK NEAR GORMAN, NC", "ELLERBE CREEK AT GORMAN, NC")) %>%
  ggplot(aes(x=str_wrap(parameter_group_nm, 20), y = Percent_Detected, fill = parameter_group_nm)) +
  geom_bar(position = "dodge", stat = "identity") +
  facet_wrap(~MonitoringLocationName) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle=45, hjust = 1), legend.position="bottom",  
        plot.caption = element_text(hjust = 0.5),
        plot.title = element_text(hjust = 0.5)) + 
  ylim(0, 100) +
  coord_flip() +
  labs(x="", y="Portion of samples below detection limit (%)", 
       title="Portion of Samples Below Detection Limit, for Detected Analytes", fill="Analyte Group", 
       caption = "'Organics, other' is inclusive of pharmaceuticals and industrial byproducts")
print(Detection_Percent)

Gorman_Detection_Percent<- Detect_Percent_Data %>% 
  ungroup() %>% 
  filter(str_detect(MonitoringLocationIdentifier, 
                    c("02086849"))) %>% 
  mutate(MonitoringLocationName = str_replace_all(MonitoringLocationName, 
                                                  "ELLERBE CREEK NEAR GORMAN, NC", "ELLERBE CREEK AT GORMAN, NC")) %>%
  ggplot(aes(x=str_wrap(parameter_group_nm, 20), y = Percent_Detected, fill = parameter_group_nm)) +
  geom_bar(position = "dodge", stat = "identity") +
  #facet_wrap(~MonitoringLocationName) +
  theme_classic() + 
  theme(axis.text.x = element_blank(), legend.position="bottom",  
        axis.title.y = element_text(size=16), axis.text.y = element_text(size=18),
        legend.text=element_text(size=16),
        plot.caption = element_text(size=16, hjust = 0.5),
        plot.title = element_text(size=16, hjust = 0.5)) + 
  ylim(0, 100) +
  #coord_flip() +
  labs(x="", y="Samples below detection limit (%)", 
       title="", fill="", 
       caption = "'Organics, other' is inclusive of pharmaceuticals and industrial byproducts")
print(Gorman_Detection_Percent)

```

# Other Things

```{r}
Two_Sites<-Both_Water_Plot_Data_2014 %>%
  filter(!is.na(Measured_Value_ugperL)) %>%
  filter(str_detect(parameter_group_nm, 
                    c("Organic"))) %>% 
  filter(!str_detect(CharacteristicName, "carbon")) %>% 
  filter(str_detect(MonitoringLocationName, "ELLERBE")) %>% 
  filter(Measured_Value_ugperL>0.085) %>% 
  group_by(CharacteristicName) %>% 
  ggplot(aes(x=reorder(str_wrap(CharacteristicName, 40), Measured_Value_ugperL), 
             y=Measured_Value_ugperL, fill=parameter_group_nm)) +
  geom_bar(stat="identity", position="dodge") +
  # scale_y_continuous(trans='log10') +
  coord_flip() +
  #geom_text(aes(label = ..count..), stat="count") +
  theme_classic() + 
  labs(title="Ellerbe Creek (Downstream), Top Organic Analytes", y="Max Measured Value (ug/L)", x=NULL)
print(Two_Sites)
```

```{r}
Two_Sites_Full_pest<-Both_Water_Plot_Data_2014 %>%
  filter(!is.na(Measured_Value_ugperL)) %>%
  filter(str_detect(parameter_group_nm, 
                    c("Organics, pesticide"))) %>% 
  filter(!str_detect(CharacteristicName, "carbon")) %>% 
  filter(str_detect(MonitoringLocationName, "ELLERBE|DAM")) %>% 
  #filter(Measured_Value_ugperL>0.085) %>% 
  group_by(CharacteristicName) %>% 
  ggplot(aes(x=reorder(str_wrap(CharacteristicName, 20), Measured_Value_ugperL), 
             y=Measured_Value_ugperL_not_min, fill=MonitoringLocationName)) +
  geom_boxplot() +
  scale_y_continuous(trans='log10') +
  theme_classic() +
  theme(axis.text.x = element_text(angle=45, hjust = 1)) +
  labs(title="Detected Pesticides", y="Measured Value (g/L)", x=NULL)
print(Two_Sites_Full_pest)
#ggsave("output/Figures/pesticides.png")

Two_Sites_Full_pharm<-Both_Water_Plot_Data_2014 %>%
  filter(!is.na(Measured_Value_ugperL)) %>%
  filter(str_detect(parameter_group_nm, c("Organics, other"))) %>% 
  filter(!str_detect(CharacteristicName, "carbon|mercury")) %>% 
  filter(str_detect(MonitoringLocationName, "ELLERBE|DAM")) %>% 
  mutate(CharacteristicName = str_replace_all(CharacteristicName, "\\(", "-")) %>% 
  mutate(CharacteristicName = str_replace_all(CharacteristicName, "\\)", "-")) %>% 
  mutate(CharacteristicName = str_replace(CharacteristicName, 
          "Morphinan-6-one, 4,5-epoxy-14-hydroxy-3-methoxy-17-methyl-, -5.alpha.--", "Oxycodone")) %>% 
  mutate(CharacteristicName = str_replace_all(CharacteristicName, 
          "Acetamide, 2--diethylamino--N--2,6-dimethylphenyl--", "Anestacon")) %>%
  #  mutate(food = replace(food, str_detect(food, "fruit"), "fruit")) %>% 
  filter(Measured_Value_ugperL>0) %>% 
  group_by(CharacteristicName) %>% 
  ggplot(aes(x=reorder(str_wrap(CharacteristicName, 25), Measured_Value_ugperL), 
                           y=Measured_Value_ugperL_not_min, fill=MonitoringLocationName)) +
  geom_boxplot() +
  scale_y_continuous(trans='log10') +
  theme_classic() +
  theme(axis.text.x = element_text(angle=45, hjust = 1)) +
  labs(title="Detected Pharmacueticals and Other Organic Analytes", y="Measured Value (g/L)", x=NULL)
print(Two_Sites_Full_pharm)

```


# Save all Figures

```{r}
ggsave("output/Figures/3-site_Rating-Curve.png", plot=Rating_Curve)
ggsave("output/Figures/Detection_Percent.png", plot=Detection_Percent)
```

