---
title: "WQP_Durham-Site-Analysis"
author: "J.Behrens"
date: "12/11/2020"
output: html_document
---
# Set-Up R Environment
```{r setup}
## Clear environment
rm(list = ls())

## Libraries
library(dataRetrieval)
library(tidyverse)
library(openxlsx)
library(leaflet)                                           
library(reshape2)
library(knitr)
library(MazamaSpatialUtils)

#Set working directory
opts_knit$set(root.dir = "C:/Users/jbehr/OneDrive - Duke University/Documents/5. R/2._WQP-EllerbeC-FlatR")
```

# Water Data

### Download Data
Note that the data was previously downloaded from the WQP, however here a file previously saved is used (code to download directly from the WQP is commented out).

*This will take a few minutes*
```{r}
#Ellerbe_Raw_Data <- readWQPdata(huc = "030202010403") # Takes awhile to load (downloaded on 12/11/2020)
#write.csv(Ellerbe_Raw_Data, "output/Data/WQP_Ellerbe_RAW.csv")

Ellerbe_Raw_Data<-read.csv("output/Data/WQP_Ellerbe_RAW.csv") 

Ellerbe_Sites<-whatWQPsites(huc = "030202010403")

#Upper_Neuse_Water_Raw<-Upper_Neuse_Raw_Data %>% 
 # filter(ActivityMediaName == "Water")
```

### Map Out Sites
```{r}
library(leaflet)
Ellerbe_Sites_StreamLake<-Ellerbe_Sites %>% 
   filter(str_detect(MonitoringLocationTypeName, 
                    "tream|ake")) #Find only stream and lake sites

Ellerbe_Sites_UPStreamLake<-Ellerbe_Sites_StreamLake %>% 
   filter(LongitudeMeasure < -78.86300)

Ellerbe_Sites_DOWNStreamLake<-Ellerbe_Sites_StreamLake  %>% 
   filter(LongitudeMeasure > -78.86300)

# All Sites
leaflet(data=Ellerbe_Sites_StreamLake) %>% 
  addProviderTiles("Esri.NatGeoWorldMap") %>%
  addCircleMarkers(~LongitudeMeasure,~LatitudeMeasure,
                   color = "red", radius=3, stroke=FALSE,
                   fillOpacity = 0.8, opacity = 0.8,
                   popup=~MonitoringLocationName)

# Upstream Sites
leaflet(data=Ellerbe_Sites_UPStreamLake) %>% 
  addProviderTiles("Esri.NatGeoWorldMap") %>%
  addCircleMarkers(~LongitudeMeasure,~LatitudeMeasure,
                   color = "red", radius=3, stroke=FALSE,
                   fillOpacity = 0.8, opacity = 0.8,
                   popup=~MonitoringLocationName)

# Downstream Sites
leaflet(data=Ellerbe_Sites_DOWNStreamLake) %>% 
  addProviderTiles("Esri.NatGeoWorldMap") %>%
  addCircleMarkers(~LongitudeMeasure,~LatitudeMeasure,
                   color = "red", radius=3, stroke=FALSE,
                   fillOpacity = 0.8, opacity = 0.8,
                   popup=~MonitoringLocationName)
```

#Comparing Sandy Creek to Ellerbe Creek

```{r}
#Sandy_Cornwallis_Raw<- readWQPdata(siteid = "USGS-0209722970")
#]Ellerbe_Gorman_Raw<- readWQPdata(siteid = "USGS-02086849")
#Flat_Bahama_Raw<- readWQPdata(siteid = "USGS-02085500")

rm(Sandy_Cornwallis, Ellerbe_Gorman, Flat_Bahama)

Sandy_Cornwallis<-Sandy_Cornwallis_Raw %>% 
  filter(str_detect(ActivityStartDate, "2014")) %>% 
  filter(ActivityMediaName == "Water") %>% 
  group_by(CharacteristicName) %>% 
  mutate(Max_Param_Value = max(ResultMeasureValue)) %>% 
  ungroup()
Sandy_Cornwallis<-Sandy_Cornwallis %>% mutate_if(sapply(Sandy_Cornwallis, is.numeric), as.factor)
  
Ellerbe_Gorman<-Ellerbe_Gorman_Raw %>% 
  filter(str_detect(ActivityStartDate, "2014"))%>% 
  filter(ActivityMediaName == "Water") %>% 
  group_by(CharacteristicName) %>% 
  mutate(Max_Param_Value = max(ResultMeasureValue)) %>% 
  ungroup()
Ellerbe_Gorman<-Ellerbe_Gorman %>% mutate_if(sapply(Ellerbe_Gorman, is.numeric), as.factor)

Flat_Bahama<-Flat_Bahama_Raw %>% 
  filter(str_detect(ActivityStartDate, "2014"))%>% 
  filter(ActivityMediaName == "Water") %>% 
  group_by(CharacteristicName) %>% 
  mutate(Max_Param_Value = max(ResultMeasureValue)) %>% 
  ungroup()
Flat_Bahama<-Flat_Bahama %>% mutate_if(sapply(Flat_Bahama, is.numeric), as.factor)

rm(parameterCdFile)
parameterCdFile<-parameterCdFile %>% 
  rename(USGSPCode = parameter_cd)

All_Sites<-full_join(Sandy_Cornwallis, Ellerbe_Gorman) %>% 
  full_join(Flat_Bahama) %>% 
  left_join(parameterCdFile)

#view(Sandy_Cornwallis %>% filter(CharacteristicName == "Sodium"))

```



```{r}
Measurements_Grouped<-All_Sites %>% 
  distinct(MonitoringLocationIdentifier, USGSPCode, .keep_all = TRUE) %>% 
  filter(!is.na(ResultMeasureValue)) %>%
  filter(!str_detect(parameter_group_nm, "Information|Stable|Sediment|Physical")) %>% 
  ggplot(aes(x=MonitoringLocationIdentifier, fill = as.character(parameter_group_nm))) +
  geom_bar() +
 # ylim(0, 700) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle=45, hjust = 1)) + 
  labs(title="Total Measurements Taken in 2014", fill="Analyte Group Name")
print(Measurements_Grouped)
##ggsave("output/Decades_EC.png")




```

```{r}
Lead_Up<-Ellerbe_Sites_UPStreamLake %>% 
  left_join(Ellerbe_Raw_Data) %>% 
  filter(!is.na(ResultMeasureValue)) %>%
  filter(ResultMeasureValue>0) %>% 
  filter(str_detect(CharacteristicName, "ead")) %>% 
  ggplot(aes(x=ActivityStartDate, y=ResultMeasureValue, colour=MonitoringLocationName)) +
  geom_point() +
  scale_x_date(date_labels = "%Y") +
  theme_classic()
print(Lead_Up)

Lead_Down<-Ellerbe_Sites_DOWNStreamLake %>% 
  left_join(Ellerbe_Raw_Data) %>% 
  filter(!is.na(ResultMeasureValue)) %>%
  filter(ResultMeasureValue>0) %>% 
  filter(str_detect(CharacteristicName, "ead")) %>% 
  ggplot(aes(x=ActivityStartDate, y=ResultMeasureValue, colour=MonitoringLocationName)) +
  geom_point() +
  scale_x_date(date_labels = "%Y") +
  theme_classic()
print(Lead_Down)



```


```{r}

library(arsenal) 
table_one <- tableby(continent ~ ., data = gapminder) 
summary(table_one, title = "Gapminder Data")
```



